# Generated by Django 5.0.6 on 2025-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='important_reminders',
            field=models.JSONField(blank=True, default=list, help_text='List of important reminders for attendees'),
        ),
    ]
