# Generated by Django 5.0.6 on 2025-05-29 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('events', 'Events'), ('community', 'Community'), ('workshops', 'Workshops'), ('networking', 'Networking'), ('leadership', 'Leadership'), ('mentorship', 'Mentorship'), ('competitions', 'Competitions'), ('education', 'Education'), ('international', 'International')], max_length=50)),
                ('drive_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='events.event')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
