# Generated by Django 5.0.6 on 2025-05-29 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Leadership', 'Leadership'), ('Success Stories', 'Success Stories'), ('Community', 'Community'), ('Events', 'Events'), ('Education', 'Education')], max_length=50)),
                ('image', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-date'],
            },
        ),
    ]
